### ISSUE TITLE
Does not work OOB on a Macbook using VSCode

### ISSUE THREAD

**Issue by jamessdixon** [TinyBlueRobots/AzureFunctions-FSharp-NET5#1]
I downloaded the repo to my Macbook, unzipped it, and opened it with VSCode.  I got the following errors:
<img width="569" alt="Screen Shot 2021-08-02 at 4 12 42 AM" src="https://user-images.githubusercontent.com/1394644/127845663-23cf05a9-5e04-4590-bb50-b667d59447f8.png">
<img width="1036" alt="Screen Shot 2021-08-02 at 4 13 17 AM" src="https://user-images.githubusercontent.com/1394644/127845677-0ea51c81-aab7-400e-849a-71ed596693e1.png">

What other dependencies do I need to install?

**Comment by JonCanning** [comment]
Did you run `dotnet tool restore` ?

**Comment by jamessdixon** [comment]
I followed the paket restore guide and got it working.  Unfortunately, it does not publish from VS code. 
<img width="1539" alt="Screen Shot 2021-08-02 at 9 58 16 AM" src="https://user-images.githubusercontent.com/1394644/127891121-ceaf6f8e-0f19-4d02-b0d3-a5f4c652f1ab.png">

**Comment by jamessdixon** [comment]
We need to get the Azure team to give better support to F#.  Thanks Jon for this repo.
