### ISSUE TITLE
Does not work OOB using Macbook and Visual Studio 2019

### ISSUE THREAD

**Issue by jamessdixon** [TinyBlueRobots/AzureFunctions-FSharp-NET5#2]
<img width="1311" alt="Screen Shot 2021-08-02 at 9 47 40 AM" src="https://user-images.githubusercontent.com/1394644/127888862-2b7f5d9a-2b05-4090-8e23-1dee915a707c.png">

**Comment by JonCanning** [comment]
I've added `build.sh`, does that help?

**Comment by jamessdixon** [comment]
I followed the paket restore guide and got it working. Unfortunately, it does not publish from VS.  There was no screen shot - the existing function on azure gets removed and nothing replaces it.

**Comment by jamessdixon** [comment]
How do you deploy this?  From GitHub?

**Comment by JonCanning** [comment]
I've updated `build.sh` to create a zip. Teasiest way to deploy is to use one of these approaches:

https://docs.microsoft.com/en-us/azure/app-service/deploy-zip

**Comment by jamessdixon** [comment]
We need to get the Azure team to give better support to F#. Thanks Jon for this repo and I will try and deploy.
